name:                hs-template
version:             0.1.0.0
github:              "githubuser/hs-template"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/hs-template#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- containers
- text
- bytestring
- template-haskell
- parsec
- filepath
- safe-exceptions
- directory
- time
- ghc
- ghc-paths

library:
  source-dirs: src

executables:
  hs-template-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-template

tests:
  hs-template-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - hs-template
